/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class github_com_stoneimagecompress_util_ImageUtil */

#ifndef _Included_github_com_stoneimagecompress_util_ImageUtil
#define _Included_github_com_stoneimagecompress_util_ImageUtil
#ifdef __cplusplus
extern "C" {
//因为c++编译器会对函数名进行重整。不然会提示找不到函数名
#include <jpeglib.h>
#endif
/*
 * Class:     github_com_stoneimagecompress_util_ImageUtil
 * Method:    compressBitmap
 * Signature: (Ljava/lang/Object;ILjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_github_com_stoneimagecompress_util_ImageUtil_compressBitmap
  (JNIEnv *, jclass, jobject, jint, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
